import os

lines = []
def w(s=""):
    lines.append(s)

w("-- Migration 188: calendar.organization_id -> calendar.tenant_id")
w("-- Renames organization_id to tenant_id across calendar, calendar_sync_events,")
w("-- and calendar_webhook_logs. FK target stays supabase.organizations.")
w("-- Also updates 4 functions that reference the old column name.")
w("")
w("BEGIN;")
w("")
w("-- 1. Rename columns")
w("ALTER TABLE public.calendar RENAME COLUMN organization_id TO tenant_id;")
w("ALTER TABLE public.calendar_sync_events RENAME COLUMN organization_id TO tenant_id;")
w("ALTER TABLE public.calendar_webhook_logs RENAME COLUMN organization_id TO tenant_id;")
w("")
w("-- 2. Rename indexes")
w("DROP INDEX IF EXISTS idx_calendar_organization;")
w("CREATE INDEX IF NOT EXISTS idx_calendar_tenant ON public.calendar (tenant_id);")
w("")
w("DROP INDEX IF EXISTS idx_sync_events_org;")
w("CREATE INDEX IF NOT EXISTS idx_sync_events_tenant ON public.calendar_sync_events (tenant_id);")
w("")
w("DROP INDEX IF EXISTS idx_webhook_logs_org;")
w("CREATE INDEX IF NOT EXISTS idx_webhook_logs_tenant ON public.calendar_webhook_logs (tenant_id);")
w("")
w("-- 3. Rename RLS policies on calendar")
w("DROP POLICY IF EXISTS calendar_org_read ON public.calendar;")
w("DROP POLICY IF EXISTS calendar_org_all ON public.calendar;")
w("")
w("CREATE POLICY calendar_tenant_read ON public.calendar")
w("  FOR SELECT USING (")
w("    tenant_id = (current_setting('request.jwt.claims', true)::jsonb ->> 'tenant_id')::uuid")
w("  );")
w("")
w("CREATE POLICY calendar_tenant_all ON public.calendar")
w("  FOR ALL USING (")
w("    tenant_id = (current_setting('request.jwt.claims', true)::jsonb ->> 'tenant_id')::uuid")
w("  );")
w("")
w("-- 4. Backfill calendar.tenant_id from schedule_slot via course_id")
w("UPDATE public.calendar c")
w("SET tenant_id = ss.tenant_id")
w("FROM public.schedule_slot ss")
w("WHERE c.course_id = ss.course_id")
w("  AND c.tenant_id IS NULL;")
w("")
w("-- 5. Default remaining NULLs to Redhouse tenant")
w("UPDATE public.calendar")
w("SET tenant_id = 'e227c1c6-b79d-43f1-b36d-89e71e509080'::uuid")
w("WHERE tenant_id IS NULL;")
w("")
w("-- 6. Make NOT NULL")
w("ALTER TABLE public.calendar ALTER COLUMN tenant_id SET NOT NULL;")
w("")
w("-- 7. Restore FK constraints")
w("ALTER TABLE public.calendar DROP CONSTRAINT IF EXISTS calendar_organization_id_fkey;")
w("ALTER TABLE public.calendar ADD CONSTRAINT calendar_tenant_id_fkey")
w("  FOREIGN KEY (tenant_id) REFERENCES supabase.organizations(id) ON DELETE CASCADE;")
w("")
w("ALTER TABLE public.calendar_sync_events DROP CONSTRAINT IF EXISTS calendar_sync_events_organization_id_fkey;")
w("ALTER TABLE public.calendar_sync_events ADD CONSTRAINT calendar_sync_events_tenant_id_fkey")
w("  FOREIGN KEY (tenant_id) REFERENCES supabase.organizations(id) ON DELETE CASCADE;")
w("")
w("ALTER TABLE public.calendar_webhook_logs DROP CONSTRAINT IF EXISTS calendar_webhook_logs_organization_id_fkey;")
w("ALTER TABLE public.calendar_webhook_logs ADD CONSTRAINT calendar_webhook_logs_tenant_id_fkey")
w("  FOREIGN KEY (tenant_id) REFERENCES supabase.organizations(id) ON DELETE CASCADE;")
w("")
w("-- 8. Update handle_calendar_slot_booking trigger function")
w("CREATE OR REPLACE FUNCTION public.handle_calendar_slot_booking()")
w("RETURNS trigger")
w("LANGUAGE plpgsql")
w("SECURITY DEFINER")
w("SET search_path = ''")
w("AS $function$")
w("BEGIN")
w("  IF NEW.booking_status = 'booked' AND (OLD.booking_status IS DISTINCT FROM 'booked') THEN")
w("    INSERT INTO public.schedule_slot_bookings (")
w("      calendar_id, schedule_slot_id, tenant_id, booked_by")
w("    ) VALUES (")
w("      NEW.id, NEW.booked_slot_id, NEW.tenant_id, NEW.booked_by")
w("    );")
w("  ELSIF NEW.booking_status IS DISTINCT FROM 'booked' AND OLD.booking_status = 'booked' THEN")
w("    DELETE FROM public.schedule_slot_bookings WHERE calendar_id = NEW.id;")
w("  END IF;")
w("  RETURN NEW;")
w("END;")
w("$function$;")
w("")
w("-- 9. Update generate_calendar_slots (was: organization_id)")
w("CREATE OR REPLACE FUNCTION public.generate_calendar_slots(")
w("  p_org_id           uuid,")
w("  p_grade            text,")
w("  p_num_slots         int,")
w("  p_start_date       date,")
w("  p_slot_time        time DEFAULT '14:00',")
w("  p_duration_minutes int DEFAULT 60,")
w("  p_capacity         int DEFAULT 5")
w(")")
w("RETURNS TABLE(slot_id uuid, slot_date date, slot_time time, status text)")
w("LANGUAGE plpgsql")
w("SECURITY DEFINER")
w("SET search_path = public")
w("AS $$")
w("DECLARE")
w("  v_i int;")
w("  v_date date;")
w("BEGIN")
w("  FOR v_i IN 0 .. (p_num_slots - 1) LOOP")
w("    v_date := p_start_date + (v_i || ' days')::interval;")
w("")
w("    INSERT INTO public.calendar (")
w("      tenant_id, grade, slot_date, slot_time, duration_minutes,")
w("      capacity, available_slots, booked_slots, status, created_by")
w("    ) VALUES (")
w("      p_org_id, p_grade, v_date, p_slot_time, p_duration_minutes,")
w("      p_capacity, p_capacity, 0, 'open', auth.uid()")
w("    )")
w("    RETURNING id, slot_date, slot_time, status INTO slot_id, slot_date, slot_time, status;")
w("")
w("    RETURN NEXT;")
w("  END LOOP;")
w("END;")
w("$$;")
w("")
w("-- 10. Update sync_calendar_event (was: organization_id)")
w("CREATE OR REPLACE FUNCTION public.sync_calendar_event(")
w("  p_org_id               uuid,")
w("  p_calendar_id          uuid,")
w("  p_external_event_id    text,")
w("  p_event_title          text,")
w("  p_event_description    text,")
w("  p_event_start          timestamptz,")
w("  p_event_end            timestamptz,")
w("  p_event_timezone       text,")
w("  p_location             text,")
w("  p_attendees            jsonb,")
w("  p_meeting_link_type    text,")
w("  p_external_updated_at  timestamptz")
w(")")
w("RETURNS TABLE(sync_event_id uuid, status text, message text)")
w("LANGUAGE plpgsql")
w("SECURITY DEFINER")
w("SET search_path = public")
w("AS $$")
w("DECLARE")
w("  v_existing_id uuid;")
w("  v_event_type  text;")
w("BEGIN")
w("  SELECT id INTO v_existing_id")
w("  FROM public.calendar_sync_events")
w("  WHERE external_event_id = p_external_event_id;")
w("")
w("  IF FOUND THEN")
w("    UPDATE public.calendar_sync_events")
w("    SET event_title = p_event_title, event_description = p_event_description,")
w("        event_start = p_event_start, event_end = p_event_end,")
w("        event_timezone = p_event_timezone, location = p_location,")
w("        attendees = p_attendees, external_updated_at = p_external_updated_at,")
w("        last_synced_at = now(), updated_at = now()")
w("    WHERE id = v_existing_id;")
w("    v_event_type := 'booking.updated';")
w("    sync_event_id := v_existing_id;")
w("  ELSE")
w("    INSERT INTO public.calendar_sync_events (")
w("      tenant_id, calendar_id, external_event_id, event_title, event_description,")
w("      event_start, event_end, event_timezone, location, attendees,")
w("      meeting_link_type, sync_status")
w("    ) VALUES (")
w("      p_org_id, p_calendar_id, p_external_event_id, p_event_title, p_event_description,")
w("      p_event_start, p_event_end, p_event_timezone, p_location, p_attendees,")
w("      p_meeting_link_type, 'synced')")
w("    RETURNING id INTO sync_event_id;")
w("    v_event_type := 'booking.created';")
w("  END IF;")
w("")
w("  INSERT INTO public.calendar_webhook_logs (")
w("    tenant_id, webhook_source, webhook_event_type, webhook_payload, processing_status, processed_at")
w("  ) VALUES (")
w("    p_org_id, 'cal_com', v_event_type,")
w("    json_build_object('external_event_id', p_external_event_id, 'event_title', p_event_title,")
w("      'event_start', p_event_start, 'event_end', p_event_end)::jsonb,")
w("    'success', now());")
w("")
w("  PERFORM pg_notify('calendar_events',")
w("    json_build_object('event', 'event_synced', 'sync_event_id', sync_event_id, 'org_id', p_org_id)::text);")
w("")
w("  status := 'success';")
w("  message := 'Event synced';")
w("  RETURN NEXT;")
w("END;")
w("$$;")
w("")
w("-- 11. Update get_org_calendar_events (was: organization_id)")
w("CREATE OR REPLACE FUNCTION public.get_org_calendar_events(")
w("  p_org_id     uuid,")
w("  p_from_date  timestamptz,")
w("  p_to_date    timestamptz")
w(")")
w("RETURNS TABLE(")
w("  sync_event_id     uuid,")
w("  event_title       text,")
w("  event_start       timestamptz,")
w("  event_end         timestamptz,")
w("  location          text,")
w("  meeting_link_url  text,")
w("  meeting_link_type text,")
w("  attendees         jsonb,")
w("  sync_status       text")
w(")")
w("LANGUAGE plpgsql")
w("SECURITY DEFINER")
w("SET search_path = public")
w("AS $$")
w("BEGIN")
w("  RETURN QUERY")
w("  SELECT cse.id, cse.event_title, cse.event_start, cse.event_end,")
w("         cse.location, cse.meeting_link_url, cse.meeting_link_type,")
w("         cse.attendees, cse.sync_status")
w("  FROM public.calendar_sync_events cse")
w("  WHERE cse.tenant_id = p_org_id")
w("    AND cse.event_start >= p_from_date")
w("    AND cse.event_end <= p_to_date")
w("    AND cse.sync_status != 'cancelled'")
w("  ORDER BY cse.event_start ASC;")
w("END;")
w("$$;")
w("")
w("-- 12. Update get_available_slots (was: c.organization_id)")
w("CREATE OR REPLACE FUNCTION public.get_available_slots(")
w("  p_org_id    uuid,")
w("  p_grade     text,")
w("  p_from_date date,")
w("  p_to_date   date")
w(")")
w("RETURNS TABLE(")
w("  id               uuid,")
w("  slot_date        date,")
w("  slot_time        time,")
w("  duration_minutes int,")
w("  available_slots  int,")
w("  capacity         int")
w(")")
w("LANGUAGE plpgsql")
w("SECURITY DEFINER")
w("SET search_path = public")
w("AS $$")
w("BEGIN")
w("  RETURN QUERY")
w("  SELECT c.id, c.slot_date, c.slot_time, c.duration_minutes,")
w("         c.available_slots, c.capacity")
w("  FROM public.calendar c")
w("  WHERE c.tenant_id = p_org_id")
w("    AND c.grade = p_grade")
w("    AND c.slot_date BETWEEN p_from_date AND p_to_date")
w("    AND c.status = 'open'")
w("    AND c.available_slots > 0;")
w("END;")
w("$$;")
w("")
w("COMMIT;")

content = "\n".join(lines) + "\n"
target = '/Users/ce/dev/rhproject-new/supabase/migrations/188_calendar_org_to_tenant.sql'
with open(target, 'w') as f:
    f.write(content)
print(f'Written {target}')
