-- Scheduled Report Email Template (Row 12)
-- HTML email template for scheduled report delivery

-- This template is used by the Edge Function that sends scheduled reports
-- It's stored as a reference for the email generation logic

/*
Email Template Structure:
- Subject: {{report_name}} - {{entity_type}} Report ({{date}})
- From: reports@redhouse.com
- To: recipients from scheduled_reports.recipients
- Attachment: report file (CSV/PDF)

HTML Template:
*/

CREATE OR REPLACE FUNCTION office_desk.get_scheduled_report_email_template(
  p_report_name TEXT,
  p_entity_type TEXT,
  p_frequency TEXT,
  p_date TEXT,
  p_download_url TEXT
) RETURNS TEXT AS $$
BEGIN
  RETURN format('
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <style>
    body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; max-width: 600px; margin: 0 auto; padding: 20px; }
    .header { background: #3182ce; color: white; padding: 20px; border-radius: 8px 8px 0 0; }
    .content { padding: 20px; border: 1px solid #e2e8f0; border-top: none; border-radius: 0 0 8px 8px; }
    .button { display: inline-block; background: #38a169; color: white; padding: 12px 24px; text-decoration: none; border-radius: 6px; margin: 16px 0; }
    .footer { margin-top: 20px; padding-top: 20px; border-top: 1px solid #e2e8f0; color: #718096; font-size: 12px; }
  </style>
</head>
<body>
  <div class="header">
    <h1 style="margin: 0; font-size: 24px;">%s</h1>
    <p style="margin: 8px 0 0 0; opacity: 0.9;">%s Report - %s</p>
  </div>
  <div class="content">
    <p>Your scheduled <strong>%s</strong> report is ready.</p>
    <p><strong>Report Date:</strong> %s</p>
    <p><strong>Frequency:</strong> %s</p>
    <a href="%s" class="button">Download Report</a>
    <p style="color: #718096; font-size: 14px;">If the button doesn''t work, copy and paste this link into your browser:</p>
    <p style="color: #3182ce; font-size: 12px; word-break: break-all;">%s</p>
  </div>
  <div class="footer">
    <p>This report was automatically generated by Redhouse Office Desk.</p>
    <p>To manage your scheduled reports, go to Settings > Reports.</p>
  </div>
</body>
</html>',
    p_report_name,
    p_entity_type,
    p_date,
    p_entity_type,
    p_date,
    p_frequency,
    p_download_url,
    p_download_url
  );
END;
$$ LANGUAGE plpgsql IMMUTABLE;
