ALTER TABLE public.website_leads ADD COLUMN IF NOT EXISTS family_first_name text;
ALTER TABLE public.website_leads ADD COLUMN IF NOT EXISTS family_last_name text;
ALTER TABLE public.website_leads ADD COLUMN IF NOT EXISTS family_email text;
ALTER TABLE public.website_leads ADD COLUMN IF NOT EXISTS family_phone text;
ALTER TABLE public.website_leads ADD COLUMN IF NOT EXISTS family_relation_to_child text;
ALTER TABLE public.website_leads ADD COLUMN IF NOT EXISTS family_primary_language text;
ALTER TABLE public.website_leads ADD COLUMN IF NOT EXISTS family_preferred_currency text;
ALTER TABLE public.website_leads ADD COLUMN IF NOT EXISTS family_primary_faith text;
ALTER TABLE public.website_leads ADD COLUMN IF NOT EXISTS child_name text;
ALTER TABLE public.website_leads ADD COLUMN IF NOT EXISTS child_year_of_birth integer;
ALTER TABLE public.website_leads ADD COLUMN IF NOT EXISTS child_country_of_citizenship text;
ALTER TABLE public.website_leads ADD COLUMN IF NOT EXISTS child_country_of_residency text;
ALTER TABLE public.website_leads ADD COLUMN IF NOT EXISTS child_preferred_core_curriculum text;
ALTER TABLE public.website_leads ADD COLUMN IF NOT EXISTS child_preferred_starting_grade text;
ALTER TABLE public.website_leads ADD COLUMN IF NOT EXISTS child_preferred_starting_year integer;
ALTER TABLE public.website_leads ADD COLUMN IF NOT EXISTS child_intake_group text;
ALTER TABLE public.website_leads ADD COLUMN IF NOT EXISTS zone_selection integer;
ALTER TABLE public.website_leads ADD COLUMN IF NOT EXISTS payment_method text CHECK (payment_method IN ('stripe', 'paypal'));
ALTER TABLE public.website_leads ADD COLUMN IF NOT EXISTS registration_id uuid;
ALTER TABLE public.website_leads ADD COLUMN IF NOT EXISTS archived_at timestamptz;
ALTER TABLE public.website_leads ADD COLUMN IF NOT EXISTS archive_reason text;
CREATE INDEX IF NOT EXISTS idx_website_leads_registration_id ON public.website_leads (registration_id) WHERE registration_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_website_leads_archived ON public.website_leads (archived_at) WHERE archived_at IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_website_leads_family_email ON public.website_leads (family_email) WHERE family_email IS NOT NULL;
ALTER TABLE public.website_leads ENABLE ROW LEVEL SECURITY;
ALTER TABLE office_desk.registrations ENABLE ROW LEVEL SECURITY;
